# Generated by Django 3.2.9 on 2022-10-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_createaccounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminName', models.CharField(max_length=50)),
                ('adminPassword', models.IntegerField(null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='createaccounts',
            name='studentNumber',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
