# Generated by Django 3.2.9 on 2022-10-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_auto_20221014_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminaccounts',
            name='adminEmail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='adminaccounts',
            name='adminPassword',
            field=models.CharField(max_length=50),
        ),
    ]
